/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Session: () => import('#controllers/session_controller'),
  CodigoAcesso: () => import('#controllers/codigo_acesso_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
}
