/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  CodigoAcesso: () => import('#controllers/codigo_acesso_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Respostas: () => import('#controllers/respostas_controller'),
  Session: () => import('#controllers/session_controller'),
}
