/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { NivelAcademico } from '#enums/nivel_academico'
import type { SituacaoMatricula } from '#enums/situacao_matricula'
import type { NotificationStatus } from '#models/notification'
import type { ModalidadePrograma } from '#enums/modalidade_programa'
import type { RelacaoFormacao } from '#enums/relacao_formacao'
import type { TempoPrimeiroEmprego } from '#enums/tempo_primeiro_emprego'
import type { FaixaSalarial } from '#enums/faixa_salarial'
import type { Setor } from '#enums/setor'
import type { RoleUsuario } from '#enums/role_usuario'

export class CursoSchema extends BaseModel {
  static $columns = ['ativo', 'codigo', 'createdAt', 'id', 'institutoId', 'nivel', 'nome', 'programaId', 'updatedAt'] as const
  $columns = CursoSchema.$columns
  @column()
  declare ativo: boolean
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutoId: number
  @column()
  declare nivel: NivelAcademico
  @column()
  declare nome: string
  @column()
  declare programaId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EgressoSchema extends BaseModel {
  static $columns = ['consentimentoEm', 'cpf', 'createdAt', 'emailPessoal', 'id', 'nomeCompleto', 'updatedAt', 'userId'] as const
  $columns = EgressoSchema.$columns
  @column.dateTime()
  declare consentimentoEm: DateTime | null
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailPessoal: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nomeCompleto: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class GestorCursoSchema extends BaseModel {
  static $columns = ['createdAt', 'cursoId', 'gestorId', 'id', 'updatedAt'] as const
  $columns = GestorCursoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cursoId: number
  @column()
  declare gestorId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class GestoreSchema extends BaseModel {
  static $columns = ['cargo', 'createdAt', 'id', 'nomeCompleto', 'updatedAt', 'userId'] as const
  $columns = GestoreSchema.$columns
  @column()
  declare cargo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nomeCompleto: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class InstitutoSchema extends BaseModel {
  static $columns = ['ativo', 'codigo', 'createdAt', 'id', 'nome', 'updatedAt'] as const
  $columns = InstitutoSchema.$columns
  @column()
  declare ativo: boolean
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoginCodeSchema extends BaseModel {
  static $columns = ['attempts', 'codeHash', 'createdAt', 'email', 'expiresAt', 'id', 'ipAddress', 'updatedAt', 'usedAt', 'userAgent'] as const
  $columns = LoginCodeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class MatriculaSchema extends BaseModel {
  static $columns = ['codigo', 'createdAt', 'cursoId', 'dataColacao', 'dataIngresso', 'egressoId', 'id', 'periodoFormatura', 'situacao', 'updatedAt'] as const
  $columns = MatriculaSchema.$columns
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cursoId: number
  @column.date()
  declare dataColacao: DateTime | null
  @column.date()
  declare dataIngresso: DateTime | null
  @column()
  declare egressoId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare periodoFormatura: string | null
  @column()
  declare situacao: SituacaoMatricula
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NotificationPreferenceSchema extends BaseModel {
  static $columns = ['channels', 'createdAt', 'id', 'notificationName', 'tenantId', 'updatedAt', 'userId'] as const
  $columns = NotificationPreferenceSchema.$columns
  @column()
  declare channels: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notificationName: string | null
  @column()
  declare tenantId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'notifiableId', 'readAt', 'seenAt', 'status', 'tenantId', 'type', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notifiableId: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime()
  declare seenAt: DateTime | null
  @column()
  declare status: NotificationStatus
  @column()
  declare tenantId: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProgramaSchema extends BaseModel {
  static $columns = ['ativo', 'codigo', 'createdAt', 'id', 'institutoId', 'modalidade', 'nome', 'sigla', 'updatedAt'] as const
  $columns = ProgramaSchema.$columns
  @column()
  declare ativo: boolean
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutoId: number
  @column()
  declare modalidade: ModalidadePrograma | null
  @column()
  declare nome: string
  @column()
  declare sigla: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RespostasCursoSchema extends BaseModel {
  static $columns = ['ano', 'createdAt', 'id', 'matriculaId', 'relacaoFormacao', 'respostaPessoaId', 'tempoPrimeiroEmprego', 'updatedAt'] as const
  $columns = RespostasCursoSchema.$columns
  @column()
  declare ano: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matriculaId: number
  @column()
  declare relacaoFormacao: RelacaoFormacao | null
  @column()
  declare respostaPessoaId: number
  @column()
  declare tempoPrimeiroEmprego: TempoPrimeiroEmprego | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RespostasPessoaSchema extends BaseModel {
  static $columns = ['ano', 'cargo', 'createdAt', 'egressoId', 'empregador', 'faixaSalarial', 'id', 'localizacaoCidade', 'localizacaoPais', 'localizacaoUf', 'registradaEm', 'setor', 'updatedAt'] as const
  $columns = RespostasPessoaSchema.$columns
  @column()
  declare ano: number
  @column()
  declare cargo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare egressoId: number
  @column()
  declare empregador: string | null
  @column()
  declare faixaSalarial: FaixaSalarial | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare localizacaoCidade: string | null
  @column()
  declare localizacaoPais: string | null
  @column()
  declare localizacaoUf: string | null
  @column.dateTime()
  declare registradaEm: DateTime
  @column()
  declare setor: Setor | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['bio', 'cidade', 'createdAt', 'email', 'fotoUrl', 'fullName', 'github', 'headline', 'id', 'lattes', 'linkedin', 'nomeSocial', 'orcid', 'pais', 'role', 'scholar', 'site', 'telefone', 'uf', 'updatedAt', 'visEmail', 'visEncontrar', 'visMapa'] as const
  $columns = UserSchema.$columns
  @column()
  declare bio: string | null
  @column()
  declare cidade: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fotoUrl: string | null
  @column()
  declare fullName: string | null
  @column()
  declare github: string | null
  @column()
  declare headline: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lattes: string | null
  @column()
  declare linkedin: string | null
  @column()
  declare nomeSocial: string | null
  @column()
  declare orcid: string | null
  @column()
  declare pais: string | null
  @column()
  declare role: RoleUsuario
  @column()
  declare scholar: string | null
  @column()
  declare site: string | null
  @column()
  declare telefone: string | null
  @column()
  declare uf: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visEmail: boolean
  @column()
  declare visEncontrar: boolean
  @column()
  declare visMapa: boolean
}
