/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type CursoTransformer from '#transformers/curso_transformer'
import type EgressoTransformer from '#transformers/egresso_transformer'
import type GestorTransformer from '#transformers/gestor_transformer'
import type MatriculaTransformer from '#transformers/matricula_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type RespostaCursoTransformer from '#transformers/resposta_curso_transformer'
import type RespostaPessoaTransformer from '#transformers/resposta_pessoa_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Curso = InferData<CursoTransformer>
  export namespace Curso {
    export type Variants = InferVariants<CursoTransformer>
  }
  export type Egresso = InferData<EgressoTransformer>
  export namespace Egresso {
    export type Variants = InferVariants<EgressoTransformer>
  }
  export type Gestor = InferData<GestorTransformer>
  export namespace Gestor {
    export type Variants = InferVariants<GestorTransformer>
  }
  export type Matricula = InferData<MatriculaTransformer>
  export namespace Matricula {
    export type Variants = InferVariants<MatriculaTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type RespostaCurso = InferData<RespostaCursoTransformer>
  export namespace RespostaCurso {
    export type Variants = InferVariants<RespostaCursoTransformer>
  }
  export type RespostaPessoa = InferData<RespostaPessoaTransformer>
  export namespace RespostaPessoa {
    export type Variants = InferVariants<RespostaPessoaTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
